### PR TITLE
build: fix environment files

### PR DESCRIPTION
**Pull request by deliaBlue**
In this PR there are three changes:

1. The `environment.yml` file now has the channels in the correct order for a good environment creation.
2. The `environment.dev.yml` file now has the correct channels in the proper order for the different packages to be installed.
3. The `environemnt.root.yml` file now has the correct channel

### CODE REVIEW

**Review by uniqueg — COMMENTED** [review]
It seems to me that this PR includes changes that haven't been merged yet. From which PR are those changes? I think we should merge that first, then this.

For the changes in the Conda env files, I have nothing to complain about from my side. The other changes I haven't reviewed, ut I feel I have reviewed them elsewhere in another PR.

**Comment by deliaBlue** [comment]
Now I see there has been a mix between branches... Each change in the PR #98  appears here  too... Don't quite know how this happened... The important changes here are the ones mentioned in the PR description. I apologize for this mess

**Comment by uniqueg** [comment]
No worries. Might be that these changes will disappear once #98 is merged (except maybe for the latest changes). Let's see. Otherwise, just merge in changes from the default branch into this branch after merging #98 and resolve the conflicts. That should definitely get rid of this. Or, create a new branch off the default branch after merging #98, add the three files, then push and create a new PR and close this one.

**Comment by deliaBlue** [comment]
After merging, #98 , the changes had disappear,  once he checks are passed, this PR will be ready to merge if approved.

**Review by uniqueg — APPROVED** [review]

**Pull request merged**
